const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.yagames_adaptivetext,
		C3.Plugins.Touch,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Anchor,
		C3.Plugins.Browser,
		C3.Plugins.Text,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.Request,
		C3.JavaScriptInEvents.EventSheet1_Event2_Act1,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.yagames_adaptivetext.Acts.SetText,
		C3.JavaScriptInEvents.EventSheet1_Event2_Act4,
		C3.JavaScriptInEvents.EventSheet1_Event3_Act1,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.Compare,
		C3.JavaScriptInEvents.EventSheet1_Event6_Act1,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.SVGPicture.Acts.SetDefaultColor
	];
};
self.C3_JsPropNameTable = [
	{Spisok_Number_1: 0},
	{Spisok_Number_10: 0},
	{Spisok_Number_11: 0},
	{Spisok_Number_12: 0},
	{Spisok_Number_13: 0},
	{Spisok_Number_14: 0},
	{Spisok_Number_15: 0},
	{Spisok_Number_16: 0},
	{Spisok_Number_17: 0},
	{Spisok_Number_18: 0},
	{Spisok_Number_19: 0},
	{Spisok_Number_2: 0},
	{Spisok_Number_20: 0},
	{Spisok_Number_3: 0},
	{Spisok_Number_4: 0},
	{Spisok_Number_5: 0},
	{Spisok_Number_6: 0},
	{Spisok_Number_7: 0},
	{Spisok_Number_8: 0},
	{Spisok_Number_9: 0},
	{Touch: 0},
	{Anchor: 0},
	{Plaseholder: 0},
	{Elipse_UpL: 0},
	{Elipse_UpR: 0},
	{Date_UI: 0},
	{Browser: 0},
	{Icon_Spisok: 0},
	{Text: 0},
	{AJAX: 0},
	{Data_Text: 0},
	{Classmate_1: 0},
	{Classmate_2: 0},
	{Classmate_3: 0},
	{Classmate_4: 0},
	{Classmate_5: 0},
	{Classmate_6: 0},
	{Classmate_7: 0},
	{Classmate_8: 0},
	{Classmate_9: 0},
	{Classmate_10: 0},
	{Classmate_11: 0},
	{Classmate_12: 0},
	{Classmate_13: 0},
	{Classmate_14: 0},
	{Classmate_15: 0},
	{Classmate_16: 0},
	{Classmate_17: 0},
	{Classmate_18: 0},
	{Classmate_19: 0},
	{Classmate_20: 0},
	{Spisok_Name_1: 0},
	{Spisok_Name_2: 0},
	{Spisok_Name_3: 0},
	{Spisok_Name_4: 0},
	{Spisok_Name_5: 0},
	{Spisok_Name_6: 0},
	{Spisok_Name_7: 0},
	{Spisok_Name_8: 0},
	{Spisok_Name_9: 0},
	{Spisok_Name_10: 0},
	{Spisok_Name_11: 0},
	{Spisok_Name_12: 0},
	{Spisok_Name_13: 0},
	{Spisok_Name_14: 0},
	{Spisok_Name_15: 0},
	{Spisok_Name_16: 0},
	{Spisok_Name_17: 0},
	{Spisok_Name_18: 0},
	{Spisok_Name_19: 0},
	{Spisok_Name_20: 0},
	{CurrentDateStr: 0},
	{Color: 0},
	{CSVData: 0},
	{NamesList: 0},
	{Username: 0}
];

self.InstanceType = {
	Spisok_Number_1: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_10: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_11: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_12: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_13: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_14: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_15: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_16: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_17: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_18: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_19: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_2: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_20: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_3: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_4: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_5: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_6: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_7: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_8: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Number_9: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Touch: class extends self.IInstance {},
	Plaseholder: class extends self.ISVGPictureInstance {},
	Elipse_UpL: class extends self.ISVGPictureInstance {},
	Elipse_UpR: class extends self.ISVGPictureInstance {},
	Date_UI: class extends self.ISVGPictureInstance {},
	Browser: class extends self.IInstance {},
	Icon_Spisok: class extends self.ISVGPictureInstance {},
	Text: class extends self.ITextInstance {},
	AJAX: class extends self.IInstance {},
	Data_Text: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Classmate_1: class extends self.ISVGPictureInstance {},
	Classmate_2: class extends self.ISVGPictureInstance {},
	Classmate_3: class extends self.ISVGPictureInstance {},
	Classmate_4: class extends self.ISVGPictureInstance {},
	Classmate_5: class extends self.ISVGPictureInstance {},
	Classmate_6: class extends self.ISVGPictureInstance {},
	Classmate_7: class extends self.ISVGPictureInstance {},
	Classmate_8: class extends self.ISVGPictureInstance {},
	Classmate_9: class extends self.ISVGPictureInstance {},
	Classmate_10: class extends self.ISVGPictureInstance {},
	Classmate_11: class extends self.ISVGPictureInstance {},
	Classmate_12: class extends self.ISVGPictureInstance {},
	Classmate_13: class extends self.ISVGPictureInstance {},
	Classmate_14: class extends self.ISVGPictureInstance {},
	Classmate_15: class extends self.ISVGPictureInstance {},
	Classmate_16: class extends self.ISVGPictureInstance {},
	Classmate_17: class extends self.ISVGPictureInstance {},
	Classmate_18: class extends self.ISVGPictureInstance {},
	Classmate_19: class extends self.ISVGPictureInstance {},
	Classmate_20: class extends self.ISVGPictureInstance {},
	Spisok_Name_1: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_2: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_3: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_4: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_5: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_6: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_7: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_8: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_9: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_10: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_11: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_12: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_13: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_14: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_15: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_16: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_17: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_18: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_19: class extends C3.Plugins.yagames_adaptivetext.Instance {},
	Spisok_Name_20: class extends C3.Plugins.yagames_adaptivetext.Instance {}
}